# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sergio Morales - Blog
email: sergio.bcoe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sergio's stream of consciousness- my ramblings, thoughts, and ideas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.sergiomorales.me" # the base hostname & protocol for your site
twitter_username: smoramed
github_username:  smora015

# Build settings
markdown: kramdown
